---
title: "data_wrangling"
author: "Mary Farina"
date: "10/22/2018"
output: html_document
---



```{r}

library(tidyverse)  # install.packages("tidyverse")

gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')

# inspect the data

library(skimr) #install.packages("skimr")
#skimr::skim(gapminder)

```


#Data wrangling

```{r}

# # filter by rows
# filter(gapminder, lifeExp < 35)
# filter(gapminder, country=='Mexico')
# filter(gapminder, country %in% c('Mexico','Brazil'))
# 
# sweden <- filter(gapminder, country=='Sweden' )
# mean(sweden$lifeExp)


#select by column
#select(gapminder, -continent, -lifeExp)

gap_cambodia <- filter(gapminder, country == 'Cambodia')
gap_cambodia2 = select(gap_cambodia, -continent, -lifeExp)

```

# Pipe operator will change your life!

```{r}

gapminder %>% head(3)

gap_cambodia <- gapminder %>% 
                filter(country == "Cambodia")  %>% 
                select(gap_cambodia, -continent, -lifeExp)

```


#Mutate

```{r}

#gapminder %>%  mutate(index = 1:nrow(gapminder))

##Challenge: find max gdp of Egypt and vietnam, create a new column.

gapminder %>%
  filter(country == "Egypt") %>%
  mutate(gdp = pop * gdpPercap) %>%
  mutate(max_gdp = max(gdp))

## you can also create multiple variables within the same mutate(), and line them up so they are easier to read:
gapminder %>%
  filter(country == "Vietnam") %>% 
  mutate(gdp     = pop * gdpPercap,
         max_gdp = max(gdp))


```



## `group_by()` groups!


```{r}

library(tidyverse)  # install.packages("tidyverse")

gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')

gdpGrouped <- gapminder %>% group_by(country)  %>%
              mutate(gdp = pop * gdpPercap,
              max_gdp = max(gdp))  %>% ungroup()



```


## `arrange()`







